apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin
        imagePullPolicy: Never
        name: phpmyadmin
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  loadBalancerIP: MINIKUBE_IP
  selector:
    app: phpmyadmin
  ports:
  - name: phpmyadmin
    port: 5000
    protocol: TCP
    targetPort: 5000

